GET http://127.0.0.1:8000/hello/2021

### Adicionar novos usuários
POST http://127.0.0.1:8082/users/
Content-Type: application/json

{
    "name": "Mario Ix",
    "email": "mhadaniya1ix@email.com",
    "password": "12345"
}

### Buscar lista de usuários 
GET http://127.0.0.1:8082/users/


### Buscar usuário por id
GET http://127.0.0.1:8082/users/1


### Editar um usuário
PUT http://127.0.0.1:8082/users/1
Content-Type: application/json

{
        "name": "Mario IIx",
        "email": "mhadaniya2ix@email.com"
}

### Apagar um usuário
DELETE http://127.0.0.1:8082/users/8


### Buscar lista de medidas
GET http://127.0.0.1:8082/measures/

### Buscar medidas de um usuário
GET http://127.0.0.1:8082/users/1/measures/

### Adicionar medidas
POST http://127.0.0.1:8082/users/1/measures/
Content-Type: application/json

{
    "height": 165,
    "weight": 78,
    "neck": 38,
    "chest": 123,
    "biceps": 34,
    "hips": 104,
    "waist": 88,
    "thighs": 58,
    "calf": 35
}
